### ISSUE TITLE
Problem social security number

### ISSUE THREAD

**Issue by charlemagne00** [stripe-samples/identity#510]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Server environment [e.g. Go, Java, Node, PHP, Python, Ruby, TypeScript]

## Additional context

Add any other context about the problem here.social security number its  just only problem I'm have.

**Comment by cjavilla-stripe** [comment]
Not enough information to help. Please reach out to support.stripe.com/contact.
